name: perfume-recommender
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - scikit-learn
  - nltk
  - transformers
  - streamlit
  - pytorch
  - matplotlib
  - pip
  - pip:
      - pylint
      - black
      - ruff
      - pre-commit
